# Generated by Django 4.2.1 on 2023-05-29 15:07

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fouroneone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128, region=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True),
        ),
    ]
