# Generated by Django 4.2.1 on 2023-06-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_review_review_date'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_films',
            field=models.ManyToManyField(blank=True, to='films.film'),
        ),
    ]
