# Generated by Django 4.2.1 on 2023-06-06 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_favorite_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite_films',
        ),
    ]
