# Generated by Django 4.2.1 on 2023-06-05 11:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_film_available_in_countries_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField()),
                ('review_date', models.DateField(default=datetime.date(2023, 6, 5))),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film', to='films.film')),
            ],
        ),
    ]
