# Generated by Django 4.2.1 on 2023-06-06 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=datetime.date(2023, 6, 6)),
        ),
    ]
