# Generated by Django 4.2.1 on 2023-06-18 17:13

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('daily_rate', models.IntegerField(blank=True, null=True)),
                ('dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_count', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('roomdates', models.ManyToManyField(blank=True, null=True, related_name='booking_room', to='visitors_app.room')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_booking', to='visitors_app.visitoruserprofile')),
            ],
        ),
    ]
