# Generated by Django 4.2.1 on 2023-06-18 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='roomdates',
            new_name='room',
        ),
    ]
