# Generated by Django 4.2.1 on 2023-06-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors_app', '0003_alter_booking_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
